# nourrir_flask/docker-compose.yml

#version: '3'
services:
  web:
    build: .
    container_name: nourrir-flask
    ports:
      - "8282:8080"
    environment:
      - OLLAMA_URL=http://192.168.2.10:11434/api/chat
# Uncomment the lines below if you need password-less Git / SSH access inside
# the container. Make sure you have run `scripts/setup_ssh_key.sh` first.
#    volumes:
#      - ~/.ssh:/root/.ssh:ro            # read-only SSH keys
#      - $SSH_AUTH_SOCK:/ssh-agent       # forward host agent socket
#    environment:
#      - SSH_AUTH_SOCK=/ssh-agent
    restart: unless-stopped
    networks:
      - ollama-net
networks:
  ollama-net:
    driver: bridge
