[build]
  command = "pip install -r requirements.txt && npm ci && npx tailwindcss -i tailwind.css -o static/styles.css && python freeze.py"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.12"
